In [1]:
from sklearn.pipeline import Pipeline
## feauture scaling
from sklearn.preprocessing import StandardScaler
## model
from sklearn.linear_model import LogisticRegression

In [4]:
steps = [('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]


In [5]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [6]:
Pipeline(steps)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [7]:
pipe = Pipeline(steps)


In [8]:
##visualize the pipeline
from sklearn import set_config
set_config(display='diagram')
pipe



Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [9]:
##creating a dataset
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)


In [10]:
X.shape

(1000, 20)

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

X_train




array([[-0.06200401,  0.00626131,  0.81415176, ...,  1.24689172,
        -0.17900285,  1.83255704],
       [-0.21968705, -1.4124517 , -1.50183692, ..., -0.3607045 ,
        -1.1798553 , -0.39275895],
       [ 0.39899216, -0.1175247 , -0.78259136, ...,  0.96779447,
        -0.72562008, -2.28577724],
       ...,
       [-1.44311529, -1.39557951, -0.87960631, ..., -2.23979163,
        -1.20240545, -0.99144228],
       [ 0.94686146, -1.73188868,  0.91339109, ...,  0.06429488,
        -1.46065958,  1.35108895],
       [ 1.18705115,  0.83332305, -0.28231204, ...,  0.31912084,
         0.64395896, -0.79062399]])

In [12]:
pipe.fit(X_train, y_train)


Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [13]:
y_pred = pipe.predict(X_test)


In [14]:
y_pred







array([1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,

## Example 2


Displaying a pipeline with standard scaler, dimensionality reduction, and a estimator

In [18]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

steps = [('scaling', StandardScaler()), ('PCA', PCA(n_components=3)), ('SVC', SVC())]

pipe2 = Pipeline(steps)


In [21]:
pipe2.fit(X_train, y_train)


Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [22]:
pipe2.predict(X_test)


array([1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,

## Complex examples of Columns Transformer

In [23]:
from sklearn.impute import SimpleImputer


In [24]:
import numpy as np


In [27]:
## numerical processing pipeline
numeric_processor = Pipeline(
    steps=[
        ('imputation_mean', SimpleImputer(missing_values=np.nan, strategy='mean')),
        ('scaler', StandardScaler())
    ]
)



In [28]:
numeric_processor


Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [29]:
## categorical processing pipeline

from sklearn.preprocessing import OneHotEncoder

categorical_processor = Pipeline(
    steps=[
        ('imputation_constant', SimpleImputer(fill_value='missing', strategy='constant')),
        ('onehot', OneHotEncoder(handle_unknown='ignore'))
    ]
)

categorical_processor



Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [30]:
## combine processing techniques
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(
    [
        ('numeric_processing', numeric_processor, ['age', 'height']),
        ('categorical', categorical_processor, ['gender', 'city'])
    ]
)

preprocessor





ColumnTransformer(transformers=[('numeric_processing',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height']),
                                ('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city'])])

In [31]:
from sklearn.pipeline import make_pipeline

pipe = make_pipeline(preprocessor, LogisticRegression())

pipe





Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('numeric_processing',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height']),
                                                 ('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city'])])),
                ('logisticregression', LogisticRegression())])